[ot-rfsim][script] updated scripts to support version builds from submodules; build script got autodetect when to clean builddir.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -27,7 +27,7 @@
 #
 # This script bootstraps a complete install of OTNS, nodes, dependencies.
 
-set -euox pipefail
+set -euo pipefail
 
 if [[ "$(uname)" == "Darwin" ]]; then
     export readonly Darwin=1
@@ -36,7 +36,8 @@ elif [[ "$(uname)" == "Linux" ]]; then
     export readonly Darwin=0
     export readonly Linux=1
 else
-    die "Unsupported OS: $(uname)"
+    echo "Unsupported OS: $(uname)"
+    exit 1
 fi
 
 # shellcheck source=script/utils.sh
@@ -53,10 +54,12 @@ fi
 # Install Go if needed
 install_package go --apt golang --brew golang || true
 
-# Do the rest via the test script
-# TODO: once MacOS supports OT versions, remove the below if.
-if [[ $Linux == 1 ]]; then
-    ./script/test py-ver-unittests
+# Do the rest via the test script, automatically
+./script/test py-ver-unittests || die "OTNS Installation/tests failed!"
+
+# Check if 'otns' command is available.
+if [[ -n $(which otns) ]]; then
+    echo "OTNS installed - use 'otns' to start it."
 else
-    ./script/test py-unittests
+    echo "OTNS installed - please add ~/go/bin to your PATH variable first, to use it."
 fi
