060-fix: [script] ensure Go build fails on compile error
Previously, the Go build was not failing on a compile error. This also
fixes the previous 'go get' usage which doesn't install anymore in
recent versions of Go (like >= 1.23).

diff --git a/script/install-otns b/script/install-otns
--- a/script/install-otns
+++ b/script/install-otns
@@ -39,8 +39,9 @@ install_otns()
     # contains spaces. (Double quotes, not single: a repo path may contain an apostrophe.)
     local ldflags="-X \"github.com/openthread/ot-ns/simulation.installedNodesDir=${OTNSDIR}/ot-rfsim/ot-versions\""
 
-    go mod tidy
-    repeat 3 go_install "-ldflags=${ldflags}" ./cmd/...
+    go mod tidy || die "'go mod tidy' failed"
+    # repeats are done to get past transient failures such as a download hiccup.
+    repeat 3 go_install "-ldflags=${ldflags}" ./cmd/... || die "building OTNS failed - see the Go build errors above"
     echo "otns installed: $(command -v otns)"
 }
 
