010-feat: locate nodes in the OTNS repo directory (#195)
The installation is updated so that OTNS can locate the OT node
executables from any directory that it is run in. The new script
'./script/install-otns' builds the absolute path of this repo's
'./ot-rfsim/ot-versions' directory into the OTNS executable, using
a Go linker flag. That path is the last entry of the executables
search path, so that node executables in the current working dir,
or in its './ot-rfsim/ot-versions' subdirectory, always take
preference over it.

In addition, the new environment variable OTNS_NODES_DIR can be set
to one or more directories that are searched before all the default
search paths for node binaries.

The build of the OT nodes is now also part of './script/install',
which installs OTNS, pyOTNS and all nodes. The OTNS-only install
that was in './script/install' moved to './script/install-otns'.

The 'repeat' and 'go_install' script functions are updated to pass
on all their arguments unmodified, which is needed to provide the
linker flag to 'go install'.

Closes issue #587

diff --git a/script/install-otns b/script/install-otns
--- a/script/install-otns
+++ b/script/install-otns
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (c) 2024-2026, The OTNS Authors.
+# Copyright (c) 2020-2026, The OTNS Authors.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -25,16 +25,38 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-# Installs the full set of OT node executables used by OTNS. This includes
-# different Thread protocol version nodes and special node types (BR).
+# Installs OTNS (without any OT node executables) and pyOTNS.
 
 # shellcheck source=script/common.sh
 . "$(dirname "$0")"/common.sh
 
+install_otns()
+{
+    # The location of this repo's node executables is built into the OTNS executable, so that the
+    # nodes built by './script/install-nodes' are found when OTNS is run from any other directory.
+    # Note: 'go' splits the -ldflags value on whitespace, honoring a quote only at the start of a
+    # field. So the -X value is given as its own double-quoted field, to allow a repo path that
+    # contains spaces. (Double quotes, not single: a repo path may contain an apostrophe.)
+    local ldflags="-X \"github.com/openthread/ot-ns/simulation.installedNodesDir=${OTNSDIR}/ot-rfsim/ot-versions\""
+
+    go mod tidy
+    repeat 3 go_install "-ldflags=${ldflags}" ./cmd/...
+    echo "otns installed: $(command -v otns)"
+}
+
+install_pyotns()
+{
+    activate_python_venv
+    cd pylibs || die "required directory 'pylibs' not found"
+    python3 -m pip install .
+    # python3 setup.py install --user --prefix= 2>/dev/null  #  alternative - fails on macos-14
+    cd - || die "cd failed"
+}
+
 main()
 {
-    build_openthread_versions
-    echo "nodes installed: ${OTNSDIR}/ot-rfsim/ot-versions"
+    install_pyotns
+    install_otns
 }
 
 main
